### ISSUE TITLE
Plans for OMP plugin

### ISSUE THREAD

**Issue by ovilla7** [withanage/UBHD-Lens#6]
Hello, I have found your implementation of this Lens for OJS plugin, I'm wondering if you have any plan to release a plugin for OMP using this Lens.

**Comment by withanage** [comment]
@ovilla7 
Actaully it supports OMP but in a different front-end, which I have written.

It is in python.
https://github.com/UB-Heidelberg/UBHD-OMPPortal

Ohererwise I do not plan to write a plugin for OMP with this, but I will upgrade it to OJS 3.2 +

It will be a big  effort to  change it to the OMP original interface.

**Comment by ovilla7** [comment]
@withanage 

Sure, it would take a lot of effort to create that plugin.

Thank you very much, I'll take a look at that other project.
